### ISSUE TITLE
Add possibility to inject usb device id's for device detection

### ISSUE THREAD

**Issue by Nicoretti** [Nicoretti/ka3005p#12]
Other power supplies might use a different usb chip manufacturer and therefore may have different id's. Therefore the possibility for overriding the usb ids for the detection of the power supply should be added.

**Comment by JackNewman12** [comment]
Note I have added a field to just manually specify the serial port itself.  https://github.com/Nicoretti/ka3005p/pull/16
That seems easier than trying to figure out what the USB ids are for different brands. 

Note I am 4 brands deep now and the USB ids have all been the same 😅 zero effort clones.

**Comment by Nicoretti** [comment]
Hi Jack,

thx for the PR, I'll try to go over it and integrate as soon as possible.

> Note I have added a field to just manually specify the serial port itself. #16
> That seems easier than trying to figure out what the USB ids are for different brands.
> 
> Note I am 4 brands deep now and the USB ids have all been the same 😅 zero effort clones.

xD these seems to be true for most non "high end" or specialised devices theses days, it all is produced in China and you mostly pay for the different branding.
