### ISSUE TITLE
Verify status bits are correct for the one channel power supply

### ISSUE THREAD

**Issue by Nicoretti** [Nicoretti/ka3005p#7]
Verifiy that all flags are match the ones documented in the ka3005p documentation

**Comment by JackNewman12** [comment]
They seem perfect to me on all the devices I have used. (multiple brands too).

However I see that some other online libraries seem to use some undocumented (as far as I can tell) bitfields in the status command to see if OCP or OVP is enabled.  Might we worth a look at this.

**Comment by Nicoretti** [comment]
Hi Jack,

sounds reasonable, I will close this ticket and I also created a ticket where we can track the investigation of the undocumented status bitflags you mentioned.

best
Nico
